version: "3"
services:
  docker-postgresql:
    build: .
    ports:
    - "8080:8080"
    volumes: 
    - ./:/app
    - /app/node_modules
    environment:
    - port=8080
    env_file:
    - ./.env
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:${DB_PORT}
    volumes:
    - postgres:/var/lib/postgresql/data
volumes:
  postgres:

